ci-cd: added workflow and readme

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -1,4 +1,4 @@
-name: Clone repo & build & start app with Docker and Notary
+name: Clone repo & build & start app with Docker
 
 on:
   workflow_call:
@@ -17,9 +17,8 @@ on:
       - main
 
 env:
-  REGISTRY: ghcr.io/PascalNehlsen
+  REGISTRY: ghcr.io/pascalnehlsen
   IMAGE_NAME: conduit
-  IMAGE_TAG: ${{ github.sha }}
   DOCKER_BUILDKIT: 1
   COMPOSE_DOCKER_CLI_BUILD: 1
   DOCKER_CONTENT_TRUST: 1
@@ -57,16 +56,23 @@ jobs:
         id: meta
         uses: docker/metadata-action@v5.6.1
         with:
-          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
+          images: |
+            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
+
+      - name: Create .env file from example.env and add GITHUB_SHA
+        run: |
+          cp ./example.env .env
+          echo "GITHUB_SHA=${{ github.sha }}" >> .env
 
       - name: Build and push Docker image for frontend
         id: frontend-build-and-push
         uses: docker/build-push-action@v6.12.0
         with:
           context: ./conduit-frontend
+          file: ./conduit-frontend/frontend.Dockerfile
           push: ${{ github.event_name != 'pull_request' }}
           tags: |
-            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/conduit-frontend:${{ env.IMAGE_TAG }}
+            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/conduit-frontend:${{ github.sha }}
           labels: ${{ steps.meta.outputs.labels }}
           cache-from: type=gha,scope=common
           cache-to: type=gha,mode=max,scope=common
@@ -76,44 +82,66 @@ jobs:
         uses: docker/build-push-action@v6.12.0
         with:
           context: ./conduit-backend
+          file: ./conduit-backend/backend.Dockerfile
           push: ${{ github.event_name != 'pull_request' }}
           tags: |
-            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/conduit-backend:${{ env.IMAGE_TAG }}
+            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/conduit-backend:${{ github.sha }}
           labels: ${{ steps.meta.outputs.labels }}
           cache-from: type=gha,scope=common
           cache-to: type=gha,mode=max,scope=common
 
-      - name: Push images (with Docker Content Trust)
-        run: |
-          echo "Pushing frontend and backend images with Docker Content Trust enabled."
-          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/conduit-frontend:${{ env.IMAGE_TAG }}
-          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/conduit-backend:${{ env.IMAGE_TAG }}
+      - name: Upload artifacts (.env and docker-compose.yaml)
+        uses: actions/upload-artifact@v4.6.0
+        with:
+          name: deployment-files
+          path: |
+            .env
+            docker-compose.yaml
+          include-hidden-files: true
+          if-no-files-found: error
 
   deploy:
     runs-on: ubuntu-latest
+    needs: build
 
     steps:
-      - name: SSH into the server and deploy with Docker Compose
-        env:
-          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
-          REMOTE_USER: ${{ secrets.REMOTE_USER }}
-          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
-          REMOTE_PATH: ${{ secrets.TARGET }}
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Download deployment artifact
+        uses: actions/download-artifact@v4.1.8
+        with:
+          name: |
+            deployment-files
+
+      - name: Set up SSH key
         run: |
-          # Ensure necessary directory exists on the remote server
-          ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY $REMOTE_USER@$REMOTE_HOST << 'EOF'
-            mkdir -p $REMOTE_PATH
+          mkdir -p ~/.ssh
+          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
+          chmod 600 ~/.ssh/id_ed25519
+
+      - name: SSH into the server and deploy with Docker Compose
+        run: |
+          # Ensure the target directory exists on the remote server with correct permissions
+          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
+            sudo mkdir -p ${{ secrets.TARGET }}
+            sudo chown -R ${{ secrets.REMOTE_USER }}:$${{ secrets.REMOTE_USER }} ${{ secrets.TARGET }}  # Ensure user has write permission
           EOF
+                  
+          # Use rsync to transfer .env and docker-compose.yaml with sudo permissions
+          rsync -avz --rsync-path="sudo rsync" .env docker-compose.yaml ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.TARGET }}/
 
-          # Copy only the docker-compose.yml to the remote server
-          rsync -avz ./docker-compose.yml $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH/
+          # Deploy the app with Docker Compose
+          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
 
-          # SSH into the server and run Docker Compose
-          ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY $REMOTE_USER@$REMOTE_HOST << 'EOF'
-            cd $REMOTE_PATH
-          echo "Starting the deployment..."
-          docker-compose down --remove-orphans || { echo "Failed to stop containers"; exit 1; }
-          docker system prune -af || { echo "Failed to prune system"; exit 1; }
-          docker-compose pull || { echo "Failed to pull images"; exit 1; }
-          docker-compose up -d || { echo "Failed to start containers"; exit 1; }
+            echo "Logging in to the registry..."
+            echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
+
+            cd ${{ secrets.TARGET }}
+
+            echo "Starting the deployment..."
+            docker compose down --remove-orphans || { echo "Failed to stop containers"; exit 1; }
+            docker system prune -af || { echo "Failed to prune system"; exit 1; }
+            docker compose pull || { echo "Failed to pull images"; exit 1; }
+            docker compose up -d || { echo "Failed to start containers"; exit 1; }
           EOF
